<?php
/* @var Training\Car\Block\Display $block */
$cars = $block->getAllCars();
?>

<form method="post" action="<?= $block->getAddCarPostUrl() ?>">
   <fieldset>
       <div>
            <label for="Marca"><?= __("Marca") ?></label>
           <input type="text" name="marca" id="marca" />
      </div>
       <div>
            <label for="modelo"><?= __("Modelo") ?>
           <input type="text" name="modelo" id="modelo" />
       </div>
      <input type="submit" value="<?= __("Add Car") ?>" />
   </fieldset>
</form>
<hr />
<?php if (count($cars) > 0): ?>
 <table border="1">
      <tr>
         <th><?= __("ID") ?></th>
          <th><?= __("Marca") ?></th>
          <th><?= __("Modelo") ?></th>
        </tr>
       <?php foreach ($cars as $car): ?>
            <tr>
               <td><?= $car->getId() ?>
               <td><?= $car->getMarca() ?>
              <td><?= $car->getModelo() ?>
           </tr>
      <?php endforeach; ?>
    </table>
<?php else: ?>
    <h1><?= __("You have no cars yet :(") ?></h1>
<?php endif; ?>